const tr = {
  header: { home: "Fiyatın Anatomisi ana sayfa", beta: "İçerik beta", betaTitle: "Teknik kaynak eşleştirmesi devam ediyor", navigation: "Ana navigasyon", mobileNavigation: "Mobil navigasyon", search: "Ara", language: "Dil seçimi", openMenu: "Menüyü aç", closeMenu: "Menüyü kapat", theme: "Tema seçimi", light: "Açık tema", dark: "Koyu tema", system: "Sistem teması" },
  article: { contents: "İçindekiler", shortInfo: "Kısa bilgiler", pros: "Artıları", cons: "Eksileri", article: "makalesi" },
  footer: { headlineBefore: "Neye para verdiğini", emphasis: "bilerek", headlineAfter: "seç.", description: "Teknolojik ürün fiyatlarını ve karmaşık terimleri bağımsız, sade ve anlaşılır bir dille açıklıyoruz.", explore: "Keşfet", transparency: "Şeffaflık", categories: "Kategoriler", guides: "Rehberler", factors: "Fiyat faktörleri", comparisons: "Karşılaştırmalar", content: "İçeriklerimiz", editorial: "Editoryal politika", privacy: "Gizlilik", contact: "İletişim", report: "Bir hata mı gördün?", notify: "Bize bildir", disclaimer: "Bağımsız eğitim platformu · Fiyat değerlendirmeleri kesin maliyet hesabı değildir." },
  product: { seeInside: "Ürünün içini gör", systemQuestion: "nasıl bir sistem?", systemLead: "Tek bir özellik değil; güç, kontrol, malzeme ve güvenlik kararlarının birlikte çalıştığı bir bütündür. Aşağıdaki harita en temel dört sistemi gösterir.", product: "Ürün", priceReason: "Fiyatı neden etkiler?", pro: "Artısı", con: "Eksisi", shortPath: "Kısa karar yolu", checklist: "Satın alırken üç kontrol", checklistText: "Bu başlığı kullanım ihtiyacın, bakım kolaylığı ve fiyat farkıyla birlikte değerlendir.", systemMap: "sistem haritası" },
  retail: { eyebrow: "Mağazada gördüğün bilgiler", title: "Mağazada gördüğün özellikler", lead: "Önce satış sayfasındaki özellikleri ve bunların fiyatı ne kadar etkilediğini oku. Teknik ayrıntıları yalnızca merak ettiğinde aç.", decisionTitle: "Önce bunlara bak", commonValues: "Yaygın değerler", priceImpact: "Fiyat etkisi", importance: "Kullanıcı için önemi", details: "Açıklama ve kaynak durumu", reviewed: "Son kontrol", impacts: { "düşük": "düşük", orta: "orta", "yüksek": "yüksek" }, sources: { editorial: "Editoryal değerlendirme", primary: "Birincil kaynak", independent: "Bağımsız kaynak" } },
  category: { world: "Ürün dünyası", term: "terim", priceQuestion: "Bu kategoride fiyatı ne büyütür?", hiddenSide: "Etiketin görünmeyen tarafı", effect: "etki", factor: "etken", estimate: "Etki seviyeleri editoryal değerlendirmedir; kesin maliyet oranı değildir.", glossary: "Teknoloji sözlüğü", learn: "Terimi öğren,", filterMarketing: "pazarlamayı ayıkla.", guides: "Satın alma rehberleri", decision: "Bilgiyi karara dönüştür.", guideLead: "Teknik özellikleri tek başına değil, kullanım amacın ve toplam maliyetle birlikte düşün.", guide: "Rehber", start: "Okumaya başla", rule: "Kısa kural", ruleText: "En pahalı özellik, sana en faydalı özellik olmayabilir.", applianceEyebrow: "Altı ayrı ürün dünyası", appliances: "Beyaz Eşya", applianceLead: "Her cihazın parçaları, enerji kullanımı ve fiyat yapısı farklıdır. İncelemek istediğin ürünü seç.", groups: ["Parçalar ve malzemeler", "Çalışma prensipleri", "Üretim ve dayanıklılık", "Enerji, bakım ve ömür", "Yazılım, bağlantı ve kullanım"] },
  search: { eyebrow: "Tüm ev teknolojileri", title: "Arama", lead: "Bir ürün, mağaza özelliği, parça, teknoloji veya rehber yaz.", label: "Arama terimi", placeholder: "Örn. 120 Hz, No Frost, LiDAR", button: "Ara", result: "sonuç", match: "eşleşme", noMatch: "Henüz bir eşleşme yok.", retry: "Daha kısa bir terim deneyebilir veya ürün gruplarından başlayabilirsin.", explore: "Ürün gruplarını keşfet", group: "Ürün grubu", brand: "Marka", content: "İçerik", labels: { term: "Teknik terim", guide: "Rehber", category: "Ürün türü", factor: "Fiyat faktörü", "retail-feature": "Mağaza özelliği" }, groups: { groups: "Ürün grupları", categories: "Ürün türleri", features: "Mağaza özellikleri", terms: "Teknik terimler", guides: "Rehberler", factors: "Fiyat faktörleri ve markalar" } },
  pricing: { eyebrow: "Donanımın ötesi", title: "Fiyat faktörleri", lead: "Etiket fiyatını dört basit katmanda incele. Başlığı açtığında o katmandaki tüm etkenleri görebilirsin.", nav: "Fiyat faktörü katmanları", effect: "etki", disclaimer: "Marka primi ve PR/pazarlama etkisi dahil bu sınıflandırmalar kesin maliyet yüzdesi değil, şeffaf editoryal değerlendirmedir.", brands: "Marka profilleri", brandTitle: "Marka, fiyatı nasıl konumlandırır?", brandLead: "Bu profiller kalite sıralaması değil, markanın pazardaki genel anlatım biçimini gösteren tarafsız başlangıç notlarıdır.", layers: { urun: ["Ürünün kendisi", "Parça, malzeme, kapasite, donanım ve yazılım."], uretim: ["Üretim ve ömür", "Üretim kalitesi, test, bakım, servis ve dayanıklılık."], satis: ["Marka ve satış", "Marka primi, lisans, reklam, PR, dağıtım ve mağaza payı."], dis: ["Dış maliyetler", "Vergi, kur, ithalat, lojistik ve enerji gibi dış etkiler."] } },
  guides: { eyebrow: "Satın alma kararından önce", title: "Rehberler", lead: "Önce ürün grubunu seç. Teknik özellikleri gerçek ihtiyaca ve toplam maliyete çeviren rehberlere hızla ulaş.", navigation: "Rehber kategorileri", count: "satın alma ve kullanım rehberi", minute: "dk" },
  visuals: { diagram: "teknolojisini anlatan basit diyagram", input: "Teknoloji girdisi", userEffect: "Kullanıcı etkisi", illustration: "teknolojileri illüstrasyonu" },
  guideDetail: { summary: "Rehber özeti", editorial: "Editoryal not", guide: "Rehber", category: "Kategori", readingTime: "Okuma süresi", sectionCount: "Bölüm sayısı", lastReview: "Son inceleme", practical: "Pratik rehber", minuteLong: "dakika", note: "Bu rehber genel eğitim amaçlıdır. Satın almadan önce üreticinin güncel belgelerini doğrula.", reviewed: "Son gözden geçirilme" },
  comparisons: { eyebrow: "İkincil araç", title: "Karşılaştırmalar", lead: "İki teknoloji arasında kaldığında pazarlama cümlelerini değil, gerçek kullanım farkını yan yana gör.", detailEyebrow: "Yan yana, sade cevap", quickResult: "Hızlı sonuç" },
  term: { back: "Kategoriye dön", kicker: "Teknoloji sözlüğü", brief: "Kısaca", analogy: "Basit benzetme:", works: "Nasıl çalışır?", price: "Fiyatı neden etkiler?", tradeoffs: "Artıları ve eksileri", audience: "Kim önemsemeli?", shouldCare: "Önem vermesi gerekenler", canSkip: "Kim ekstra para vermemeli?", assessment: "Editoryal değerlendirme", assessmentNote: "Bu puanlar mutlak teknik ölçüm değil, ortalama kullanım için açıklamalı değerlendirmedir.", impact: "Fiyata etkisi", benefit: "Kullanıcı faydası", importance: "Ortalama kullanıcı için önem", sources: "Kaynaklar", sourceNote: "Bu ilk içerik paketi editoryal taslaktır. Üretici ve standart belgeleri terim bazında eşleştirilmeden yayımlanmış teknik kaynak olarak değerlendirilmemelidir.", reviewed: "Son gözden geçirilme", category: "Kategori", lastReview: "Son inceleme", term: "Terim" },
};

const en = {
  header: { home: "Anatomy of Price home page", beta: "Content beta", betaTitle: "Technical source matching is in progress", navigation: "Main navigation", mobileNavigation: "Mobile navigation", search: "Search", language: "Language selection", openMenu: "Open menu", closeMenu: "Close menu", theme: "Theme selection", light: "Light theme", dark: "Dark theme", system: "System theme" },
  article: { contents: "Contents", shortInfo: "Quick facts", pros: "Advantages", cons: "Disadvantages", article: "article" },
  footer: { headlineBefore: "Choose with clarity about", emphasis: "what you pay for", headlineAfter: ".", description: "We explain technology prices and complex terms independently, clearly, and in plain language.", explore: "Explore", transparency: "Transparency", categories: "Categories", guides: "Guides", factors: "Price factors", comparisons: "Comparisons", content: "Our content", editorial: "Editorial policy", privacy: "Privacy", contact: "Contact", report: "Found an error?", notify: "Tell us", disclaimer: "Independent education platform · Price assessments are not exact cost calculations." },
  product: { seeInside: "See inside the product", systemQuestion: "as a system", systemLead: "A product is not one specification. Power, control, materials, and safety decisions work together. This map shows four core systems.", product: "Product", priceReason: "Why does it affect price?", pro: "Advantage", con: "Disadvantage", shortPath: "A short decision path", checklist: "Three checks before buying", checklistText: "Consider this together with your needs, maintenance effort, and the price difference.", systemMap: "system map" },
  retail: { eyebrow: "What you see in stores", title: "Features shown in stores", lead: "Start with the specifications on the product page and how much they affect price. Open technical detail only when you need it.", decisionTitle: "Check these first", commonValues: "Common values", priceImpact: "Price impact", importance: "User importance", details: "Explanation and source status", reviewed: "Last checked", impacts: { "düşük": "low", orta: "medium", "yüksek": "high" }, sources: { editorial: "Editorial assessment", primary: "Primary source", independent: "Independent source" } },
  category: { world: "Product category", term: "terms", priceQuestion: "What increases the price in this category?", hiddenSide: "What the price tag does not show", effect: "impact", factor: "factors", estimate: "Impact levels are editorial assessments, not exact cost percentages.", glossary: "Technology glossary", learn: "Learn the term,", filterMarketing: "filter the marketing.", guides: "Buying guides", decision: "Turn information into a decision.", guideLead: "Consider specifications together with your use case and total ownership cost.", guide: "Guide", start: "Start reading", rule: "Simple rule", ruleText: "The most expensive feature may not be the most useful one for you.", applianceEyebrow: "Six distinct product categories", appliances: "Major Appliances", applianceLead: "Each appliance has a different set of parts, energy needs, and price structure. Choose the product you want to examine.", groups: ["Parts and materials", "How it works", "Manufacturing and durability", "Energy, maintenance and lifespan", "Software, connectivity and use"] },
  search: { eyebrow: "All home technology", title: "Search", lead: "Search for a product, store specification, part, technology, or guide.", label: "Search term", placeholder: "E.g. 120 Hz, No Frost, LiDAR", button: "Search", result: "results", match: "matches", noMatch: "No match yet.", retry: "Try a shorter term or begin with the product groups.", explore: "Explore product groups", group: "Product group", brand: "Brand", content: "Content", labels: { term: "Technical term", guide: "Guide", category: "Product type", factor: "Price factor", "retail-feature": "Store feature" }, groups: { groups: "Product groups", categories: "Product types", features: "Store features", terms: "Technical terms", guides: "Guides", factors: "Price factors and brands" } },
  pricing: { eyebrow: "Beyond the hardware", title: "Price factors", lead: "Examine the price tag in four simple layers. Open a layer to see every factor inside it.", nav: "Price factor layers", effect: "impact", disclaimer: "These classifications, including brand premium and marketing impact, are transparent editorial assessments rather than exact cost percentages.", brands: "Brand profiles", brandTitle: "How does a brand position its price?", brandLead: "These profiles are not quality rankings. They are neutral starting notes about how a brand is positioned in the market.", layers: { urun: ["The product itself", "Parts, materials, capacity, hardware, and software."], uretim: ["Manufacturing and lifespan", "Manufacturing quality, testing, maintenance, service, and durability."], satis: ["Brand and sales", "Brand premium, licensing, advertising, PR, distribution, and retail margin."], dis: ["External costs", "Tax, exchange rates, imports, logistics, and energy." ] } },
  guides: { eyebrow: "Before you buy", title: "Guides", lead: "Choose a product group first. Quickly reach guides that translate specifications into real needs and total cost.", navigation: "Guide categories", count: "buying and usage guides", minute: "min" },
  visuals: { diagram: "simple technology diagram", input: "Technology input", userEffect: "User impact", illustration: "technology illustration" },
  guideDetail: { summary: "Guide summary", editorial: "Editorial note", guide: "Guide", category: "Category", readingTime: "Reading time", sectionCount: "Number of sections", lastReview: "Last review", practical: "Practical guide", minuteLong: "minutes", note: "This guide is for general education. Check the manufacturer's current documents before buying.", reviewed: "Last reviewed" },
  comparisons: { eyebrow: "Supporting tool", title: "Comparisons", lead: "When choosing between two technologies, compare the real differences in use instead of marketing claims.", detailEyebrow: "Side by side, in plain language", quickResult: "Quick result" },
  term: { back: "Back to category", kicker: "Technology glossary", brief: "In brief", analogy: "Simple analogy:", works: "How does it work?", price: "Why does it affect price?", tradeoffs: "Advantages and disadvantages", audience: "Who should care?", shouldCare: "Who should pay attention", canSkip: "Who should not pay extra?", assessment: "Editorial assessment", assessmentNote: "These scores are explanatory editorial assessments for average use, not absolute technical measurements.", impact: "Price impact", benefit: "User benefit", importance: "Importance for the average user", sources: "Sources", sourceNote: "This initial content package is an editorial draft. It should not be treated as verified technical sourcing until manufacturer and standards documents are matched term by term.", reviewed: "Last reviewed", category: "Category", lastReview: "Last review", term: "Term" },
};

export const uiCopy = { tr, en };
export function getUiCopy(locale) { return uiCopy[locale] || uiCopy.tr; }
